version: '3.3'

services:
    kafkamgr:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: kafkamgr
                FROM_BASE: ${DOCKER_REGISTRY:-}openjdk/8.171.11-r0:${BASE_TAG:-latest}
                KM_ARGS: '-Djava.net.preferIPv4Stack=true -Dapplication.home=/usr/local/kafka-manager/home'
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}openjdk/8.171.11-r0:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.branch: $CONTAINER_GIT_BRANCH
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: kafka-manager
        container_name: kafkamgr
        environment:
            APPLICATION_SECRET: letmein
#            BASE_ZK_PATH:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            CONSUMER_PROPERTIES_FILE: /usr/local/kafka-manager/conf/consumer.properties
            KAFKA_MANAGER_PASSWORD: password
            KAFKA_MANAGER_USERNAME: admin
            KAFKA_MANAGER_AUTH_ENABLED: 'false'
            KAFKA_MANAGER_LOGLEVEL: INFO
#            KM_HTTP_CONTEXT: /
            KM_HTTP_CONTEXT: /kafkamgr
            ZK_HOSTS: zookeeper:2181,10.1.3.6:2181,10.1.3.11:2181
        hostname: kafkamgr
        image: ${DOCKER_REGISTRY:-}kafka-manager/1.3.3.18:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 9000:9000
        volumes:
            - ./vols/log:/usr/local/kafka-manager/home 