version: '3.5'

services:
    kafkamgr2:
        build:
            args:
                CONTAINER_NAME: kafkamgr
                CONTAINER_VERSION: 1.0.6
                DEBUG_TRACE: 0
                FROM_BASE: openjdk_8u131.11-r2:20180314
                KM_ARGS: '-Djava.net.preferIPv4Stack=true -Dapplication.home=/usr/local/kafka-manager/home' 
                KM_VERSION: 1.3.3.16
            cache_from:
                - alpine:3.6
                - base_container:20180314
                - openjdk_8u131.11-r2:20180314
            context: .
            dockerfile: Dockerfile
        container_name: kafkamgr2
        environment:
            APPLICATION_SECRET: letmein
            ZK_HOSTS: 10.1.3.6:2181,10.1.3.11:2181
            CONSUMER_PROPERTIES_FILE: /usr/local/kafka-manager/conf/consumer.properties
            KAFKA_MANAGER_PASSWORD: password
            KAFKA_MANAGER_USERNAME: admin
            KAFKA_MANAGER_AUTH_ENABLED: 'false'
#            BASE_ZK_PATH: 
            KAFKA_MANAGER_LOGLEVEL: INFO
            KM_HTTP_CONTEXT: /
            KM_HTTP_CONTEXT: /kafkamgr
        hostname: kafkamgr2
        image: kafkamgr2:20180314
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8106:9000
        restart: unless-stopped
        volumes:
            - ./vols/log:/usr/local/kafka-manager/home 