version: '3.5'

services:
    kafkamgr:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: kafkamgr
                CONTAINER_VERSION: 1.0.6
                FROM_BASE: openjdk_8u131.11-r2:latest
                KM_ARGS: '-Djava.net.preferIPv4Stack=true -Dapplication.home=/usr/local/kafka-manager/home' 
            cache_from:
                - alpine:3.6
                - base_container:latest
                - openjdk_8u131.11-r2:latest
            context: .
            dockerfile: Dockerfile
        container_name: kafkamgr
        environment:
            APPLICATION_SECRET: letmein
#            BASE_ZK_PATH: 
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            CONSUMER_PROPERTIES_FILE: /usr/local/kafka-manager/conf/consumer.properties
            KAFKA_MANAGER_PASSWORD: password
            KAFKA_MANAGER_USERNAME: admin
            KAFKA_MANAGER_AUTH_ENABLED: 'false'
            KAFKA_MANAGER_LOGLEVEL: INFO
            KM_HTTP_CONTEXT: /
#            KM_HTTP_CONTEXT: /kafkamgr
            ZK_HOSTS: 10.1.3.6:2181,10.1.3.11:2181
        hostname: kafkamgr
        image: kafkamgr:latest
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8106:9000
        restart: unless-stopped
        volumes:
            - ./vols/log:/usr/local/kafka-manager/home 