version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    kafkamgr:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: kafkamgr
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
                KM_ARGS: '-Djava.net.preferIPv4Stack=true -Dapplication.home=/usr/local/kafka-manager/home'
                KM_VERSION: ${KM_VERSION:-1.3.3.18}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: kafka-manager
                version.cbf: $CBF_VERSION
# common arguments, for building and deploy 
        container_name: kafkamgr
        environment:
            APPLICATION_SECRET: letmein
#            BASE_ZK_PATH:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            CONSUMER_PROPERTIES_FILE: /usr/local/kafka-manager/conf/consumer.properties
            KAFKA_MANAGER_PASSWORD_FILE: /run/secrets/kafka_manager.pwd
            KAFKA_MANAGER_USERNAME: admin
            KAFKA_MANAGER_AUTH_ENABLED: 'false'
            KAFKA_MANAGER_LOGLEVEL: INFO
#            KM_HTTP_CONTEXT: /
            KM_HTTP_CONTEXT: /kafkamgr
            ZK_HOSTS: zookeeper:2181
        hostname: kafkamgr
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/kafka-manager/${KM_VERSION:-1.3.3.18}:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - 9000:9000
        restart: unless-stopped               # only use when building a 'service container'
        secrets:                              # references to 'secrets' section below 
            - kafka_manager.pwd
        volumes:
            - ./vols/log:/usr/local/kafka-manager/home             # do not save aplication logs inside container 

# secrets only needed for deploy
secrets:
   kafka_manager.pwd:
     file: ~/.inf/secrets/bobb.password
