version: '3.5'

services:
    kafkamgr:
        build:
            args:
                CONTAINER_NAME: kafkamgr
                CONTAINER_VERSION: 1.0.0
                DEBUG_TRACE: 0
                FROM_BASE: openjdk_8u131.11-r2:20180311
                KM_ARGS: '-Djava.net.preferIPv4Stack=true -Dapplication.home=/kafka-manager/home' 
#                CONSUMER_PROPERTIES_FILE:
#                KAFKA_MANAGER_PASSWORD:
#                KAFKA_MANAGER_USERNAME:
#                KAFKA_MANAGER_AUTH_ENABLED:
#                BASE_ZK_PATH:
#                KAFKA_MANAGER_LOGLEVEL:
#                KM_HTTP_CONTEXT: /kafkamgr
                KM_VERSION: 1.3.3.16
            cache_from:
                - alpine:3.6
                - base_container:20180311
                - openjdk_8u131.11-r2:20180311
            context: .
            dockerfile: Dockerfile
        container_name: kafkamgr
        environment:
            APPLICATION_SECRET: letmein
            ZK_HOSTS: zookeeper:2181,10.1.3.11:2181
        hostname: kafkamgr
        image: kafkamgr:20180311
#        image: sheepkiller/kafka-manager:alpine
#        links:
#            - zookeeper:zookeeper
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8006:9000
        restart: unless-stopped
        volumes:
            - ./vols/log:/kafka-manager/home


#    kafkamgr:
#        container_name: kafkamgr
#        environment:
#            APPLICATION_SECRET: letmein
#            KM_CONTEXT: '/kafkamgr'
#            KM_ARGS: '-Dplay.http.context="/kafkamgr" -Djava.net.preferIPv4Stack=true'
#            ZK_HOSTS: zookeeper:2181,10.1.3.11:2181
#        hostname: kafkamgr
#        image: sheepkiller/kafka-manager:alpine
#        links:
#            - zookeeper:zookeeper
#        logging:
#            driver: json-file
#            options:
#                max-size: "10m"
#                max-file: "3"
#        ports:
#            - 8006:9000
#        restart: unless-stopped

